language: node_js
node_js:
  - 8
  - 10
  - lts/*
services:
  - mongodb
  - docker

before_install:
  - docker run -d --rm --cap-add=IPC_LOCK -e 'SKIP_SETCAP=yes' -e 'VAULT_DEV_ROOT_TOKEN_ID=insecureRootTestingToken' -p8200:8200 vault
  - docker ps -a

env:
  global:
    - VAULT_DEV_ROOT_TOKEN_ID=insecureRootTestingToken
    - MONGO_CONNECTION_STRING=mongodb://localhost:27017/mongoose-vault-test
    - VAULT_CONNECTION_STRING=http://localhost:8200